# Generated by Django 2.2.5 on 2019-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(choices=[(0, 'Statement'), (1, 'Doubt'), (2, 'Imp')], default=0, max_length=200, unique=True),
        ),
    ]
